-- 创建用户表：用于邮箱验证码登录与用户信息维护。
USE trip_assistant;

CREATE TABLE IF NOT EXISTS t_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '用户主键ID',
    email VARCHAR(128) NOT NULL UNIQUE COMMENT '登录邮箱，唯一',
    nickname VARCHAR(64) NOT NULL COMMENT '用户昵称',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
